name: 'Install Orocos KDL'
description: 'Install Orocos KDL for CI'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxi-dev

    - name: Install FreeGLUT
      shell: bash
      run: |
        git clone https://github.com/freeglut/freeglut
        cd freeglut
        git checkout v3.4.0
        mkdir build && cd build
        cmake .. && make -j8
        sudo make install

    - name: Install gtkmm
      shell: bash
      run: |
        sudo apt-get install -y libgtkmm-3.0-dev